#!/bin/bash 

# This script makes a .txt ascii version of every png in ./ and makes an output in ./ to place them

mkdir ./asciiimage
for file in *.png
do
	# jp2a "$file" --color -f --term-fit --background=light | cat > ./asciiimage/"$file".txt

	# jp2a "$file" --color -f --term-fit --background=dark --invert | cat > ./asciiimage/"$file".txt

	jp2a "$file" --color -f --term-fit --background=dark  | cat > ./asciiimage/"$file".txt
done
