#!/bin/bash



for webp in *.webp
do
	mkdir "$webp-gif"
	convert --coalesce $webp "$webp-png".jpg
	# rm *0.png
	mv *jpg ./$webp-gif
	cd ./$webp-gif 

	# aimagefill
	# cd ./aimagefill

	jasciiimage
	cd ./jasciiimage

	# makeasciiconvert
	# cd ./makeasciiconvert

	screenshotascii 
	cd screenoutput
	convert -resize 786x576 -delay 25 *.jpg output.gif
	cd ../../../
done 

