#!/bin/bash 

# This script makes a .txt ascii version of every png in ./ and makes an output in ./ to place them

mkdir ./jaimagefill
for file in *.jpg
do
	jp2a "$file" --color --background=dark  --fill | cat > ./jaimagefill/"$file".txt
done
