#!/bin/bash 

# This script makes a .txt ascii version of every png in ./ and makes an output in ./ to place them

mkdir ./jmakeasciiconvert
for file in *.jpg
do
	ascii-image-converter "$file" -b --threshold 30 -c -C | cat > ./jmakeasciiconvert/"$file".txt
done
