#!/bin/bash 

# This script makes a .txt ascii version of every png in ./ and makes an output in ./ to place them

mkdir ./makeasciiconvert
for file in *.png
do
	ascii-image-converter "$file" -b --threshold 30 -c -C | cat > ./makeasciiconvert/"$file".txt
done
